// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5Y7HFp76Bs2P2QJ9INR2s4eZvw25B28',
    appId: '1:790417579721:web:f8b4adbd60c55ee88cb718',
    messagingSenderId: '790417579721',
    projectId: 'nestjs-better-auth-flutter',
    authDomain: 'nestjs-better-auth-flutter.firebaseapp.com',
    storageBucket: 'nestjs-better-auth-flutter.firebasestorage.app',
    measurementId: 'G-DQ3PQN2DG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2lHK5NYTXkJsCXDXAgoyLrUzVzWY7y-Y',
    appId: '1:790417579721:android:249e055b8b42dce98cb718',
    messagingSenderId: '790417579721',
    projectId: 'nestjs-better-auth-flutter',
    storageBucket: 'nestjs-better-auth-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsbIlofGxpZzwSB87d0FXJ-l0kx7-ItIc',
    appId: '1:790417579721:ios:d5a54ae0248c60178cb718',
    messagingSenderId: '790417579721',
    projectId: 'nestjs-better-auth-flutter',
    storageBucket: 'nestjs-better-auth-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsbIlofGxpZzwSB87d0FXJ-l0kx7-ItIc',
    appId: '1:790417579721:ios:d5a54ae0248c60178cb718',
    messagingSenderId: '790417579721',
    projectId: 'nestjs-better-auth-flutter',
    storageBucket: 'nestjs-better-auth-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5Y7HFp76Bs2P2QJ9INR2s4eZvw25B28',
    appId: '1:790417579721:web:1c57f732d7930eec8cb718',
    messagingSenderId: '790417579721',
    projectId: 'nestjs-better-auth-flutter',
    authDomain: 'nestjs-better-auth-flutter.firebaseapp.com',
    storageBucket: 'nestjs-better-auth-flutter.firebasestorage.app',
    measurementId: 'G-2YJW3YYVRQ',
  );
}
